name    'DanielRedOak-logstash-forwarder'
version '0.3.1'
source 'https://github.com/davidmarquis/puppet-logstash-forwarder'
author 'DanielRedOak'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring logstash-forwarder'
description 'Module for managing and configuring logstash-forwarder, forked from electrical, MixMuffins and DanielRedOak modules on GitHub'
project_page 'https://github.com/davidmarquis/puppet-logstash-forwarder'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'rodjek/logrotate', '>= 1.1.1'
